### PR TITLE
MNT: Fix astropy dev failure

### PR DESCRIPTION
**Pull request by pllim**
Astropy dev job was failing.

### CODE REVIEW

**Comment by funbaker** [comment]
Is this related to https://github.com/astropy/ccdproc/pull/650/files#diff-85d727eee8b1f5a2e969b3d4c5c52c6eR9 ?

**Comment by pllim** [comment]
This was originally motivated by compatibility issue with Astropy core after refactoring upstream.

**Comment by cbanek** [comment]
LGTM.  I would love it if we could merge this, since it would make the build run clean and give us the ability to publish a new version.

**Comment by timj** [comment]
@RayPlante can you tell us who the maintainers are for pyvo?

**Comment by msdemlei** [comment]
On Wed, May 15, 2019 at 10:04:09AM +0000, Tim Jenness wrote:
> @RayPlante can you tell us who the maintainers are for pyvo?

For the last couple of years, @funbaker has done quite a bit of
development on U Heidelberg funding.  Unfortunately, that's run out
now, so he's only doing the most pressing things at this time.
I'm sure it'd be highly appreciated if someone else were to help out
or even take over.

       -- Markus

**Comment by RayPlante** [comment]
What Markus (@msdemlei) said.  Good to know about recent change in UH funding.  Feel free to tag me on pressing issues are PRs.

**Comment by funbaker** [comment]
> On Wed, May 15, 2019 at 10:04:09AM +0000, Tim Jenness wrote: @RayPlante can you tell us who the maintainers are for pyvo?
> For the last couple of years, @funbaker has done quite a bit of development on U Heidelberg funding. Unfortunately, that's run out now, so he's only doing the most pressing things at this time. I'm sure it'd be highly appreciated if someone else were to help out or even take over.

That, and i was laying in bed the last two weeks, hence no reaction from me.

**Comment by timj** [comment]
Not knowing where else to mention this, but last week at IVOA @msdemlei, @cbanek, representatives from ESAC, and CADC, and Astroquery developers discussed the future of pyvo and we came up with a plan of moving pyvo to the Astropy org and changing Astroquery so that it depends on pyvo. @RayPlante was also kept in the loop.

**Comment by pllim** [comment]
Sorry to hear, @funbaker . Hope you are feeling better!

**Pull request merged**
