### PR TITLE
Adding TAP Support

### PR DESCRIPTION
**Pull request by funbaker**

### CODE REVIEW

**Comment by funbaker** [comment]
It looks like the build fails because it doesn't use the updated .travis.yml

**Comment by RayPlante** [comment]
@funbaker Thanks for keeping this work going!  I'd like to get the travis builds clean again before we merge.  I'm going to put some time into this.

**Comment by funbaker** [comment]
Ok. I stil got some small changes in the pipeline, but I’ll let you know as soon as that is done.

**Comment by funbaker** [comment]
This branch is ready.

**Comment by RayPlante** [comment]
@funbaker I got travis builds working again.  Try merging the latest pyvo master changes into your fork to see if this triggers a new travis build with my fixes included.

**Comment by funbaker** [comment]
@RayPlante error 1 is my fault and easy to fix. error 2 is a bit more complicated, and may be related to astropy. gonna check.

**Comment by RayPlante** [comment]
Okay--So we're failing with python 2.6 on the lack of OrderedDict (added in 2.7).  Given that a) OrderedDict is pretty darn useful, and b) astropy has stopped supporting 2.6, we should do the same.  Let me update travis and documentation accordingly.  

It might be a good idea to do one last per-TAP, python 2.6 supporting release.  I'll create a branch for this so that we can merge the TAP support into master.

**Comment by RayPlante** [comment]
@funbaker Thanks a 10^6 for this great work!

**Comment by funbaker** [comment]
@RayPlante no problem :)
After the merge, i added a commit that reverts the dict comprehension fallback for python2.6, but thats more a cosmetic change anyway.

**Comment by RayPlante** [comment]
Yes, I noticed that.  No worries.

**Pull request merged**
